### ISSUE TITLE
Opening FBSpNOsor tab crashes settings

### ISSUE THREAD

**Issue by Emalix** [jacobcxdev/FBSpNOsor#3]
Tweak functions as intended, although attempting to open the tweaks tab in settings crashes the settings app.

Bug is on ios 12.4.8, iPhone 6, unc0ver v5.3.1

**Comment by jacobcxdev** [comment]
Does this still happen?

**Comment by ikkatto** [comment]
> Tweak functions as intended, although attempting to open the tweaks tab in settings crashes the settings app.
> 
> Bug is on ios 12.4.8, iPhone 6, unc0ver v5.3.1

I've installed this tweak on two iPhones. Like you've said, the tweak works but the tweak tab in setting keeps crashing. 
Bug is on ios 12.5.1, iPhone 6 Plus, checkra1n v0.12.2

**Comment by jacobcxdev** [comment]
> > Tweak functions as intended, although attempting to open the tweaks tab in settings crashes the settings app.
> 
> > 
> 
> > Bug is on ios 12.4.8, iPhone 6, unc0ver v5.3.1
> 
> 
> 
> I've installed this tweak on two iPhones. Like you've said, the tweak works but the tweak tab in setting keeps crashing. 
> 
> Bug is on ios 12.5.1, iPhone 6 Plus, checkra1n v0.12.2

Are you able to send any crash logs (produced by Cr4shed)?

**Comment by ikkatto** [comment]
https://pastebin.com/k13Dx3zk

**Comment by jacobcxdev** [comment]
~~I see the crash seems to happen in a dylib named `cy-jxeX3i.dylib`:~~
![image](https://user-images.githubusercontent.com/27970288/107056773-98d3bc80-67ca-11eb-9c19-a366b2180e41.png)

~~Would you be able to upload this here?~~

~~Thanks.~~

EDIT: Turns out the aforementioned dylib is a substrate utility, and this was not the issue.

**Comment by jacobcxdev** [comment]
I've just tried rebuilding libJCX, hopefully for the correct target. Are you able to install [this](https://github.com/jacobcxdev/FBSpNOsor/files/5936003/com.jacobcxdev.libjcx_1.1.1_iphoneos-arm.deb.zip) and check if it works?

**Comment by ikkatto** [comment]
> I've just tried rebuilding libJCX, hopefully for the correct target. Are you able to install [this](https://github.com/jacobcxdev/FBSpNOsor/files/5936003/com.jacobcxdev.libjcx_1.1.1_iphoneos-arm.deb.zip) and check if it works?

It finally worked!
