### ISSUE TITLE
Preferences crash

### ISSUE THREAD

**Issue by Ryutso** [jacobcxdev/FBSpNOsor#5]
Clicking into the preferences tab for this crashes the preference app.

IOS: 13.5
iPhone XS Max
Unc0ver 6.1.1

**Comment by jacobcxdev** [comment]
Could you please provide a crash log?

**Comment by Ryutso** [comment]
> Could you please provide a crash log?

I cleared Cr4shed to try to replicate and get a new log and now it's working. Unsure what happened.
